name 'php'
maintainer 'Chef Software, Inc'
maintainer_email 'cookbooks@chef.io'
license 'Apache 2.0'
description 'manages php and php modules'
version '1.5.0'

depends 'yum-remi-chef'
depends 'build-essential'
depends 'yum-epel'
depends 'mysql'
